FROM openjdk:8-jdk-alpine

VOLUME /tmp

ARG DATASOURCE_URL_ARG="jdbc:mysql://192.168.99.100:3306/greeting-schema?useSSL=false"
ARG DATASOURCE_USERNAME_ARG="root"
ARG DATASOURCE_PASSWORD_ARG=""
ARG DATASOURCE_DRIVER_NAME_ARG="com.mysql.jdbc.Driver"
ARG DATASOURCE_DIALECT_ARG="org.hibernate.dialect.MySQL5Dialect"
ARG DATASOURCE_DDL_AUTO_ARG="update"

COPY build/docker/app.jar app.jar

ENV DATASOURCE_URL=$DATASOURCE_URL_ARG
ENV DATASOURCE_USERNAME=$DATASOURCE_USERNAME_ARG
ENV DATASOURCE_PASSWORD=$DATASOURCE_PASSWORD_ARG
ENV DATASOURCE_DRIVER_NAME=$DATASOURCE_DRIVER_NAME_ARG
ENV DATASOURCE_DIALECT=$DATASOURCE_DIALECT_ARG
ENV DATASOURCE_DDL_AUTO=$DATASOURCE_DDL_AUTO_ARG

RUN sh -c 'touch /app.jar'
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]
