server.port: 8080

spring:
  profiles:
    active: "prod"
  datasource.url: ${DATASOURCE_URL}
  datasource.username: ${DATASOURCE_USERNAME}
  datasource.password: ${DATASOURCE_PASSWORD}
  datasource.driver-class-name: ${DATASOURCE_DRIVER_NAME}
  jpa.properties.hibernate.dialect: ${DATASOURCE_DIALECT}
  jpa.hibernate.ddl-auto: ${DATASOURCE_DDL_AUTO}

---

spring:
  profiles: "test"
  jpa.hibernate.ddl-auto: "create-drop"