server.port: 8080

spring.datasource.url: ${DATASOURCE_URL}
spring.datasource.username: ${DATASOURCE_USERNAME}
spring.datasource.password: ${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name: ${DATASOURCE_DRIVER_NAME}
spring.jpa.properties.hibernate.dialect: ${DATASOURCE_DIALECT}
spring.jpa.hibernate.ddl-auto: ${DATASOURCE_DDL_AUTO}

spring:
  profiles: "test"
  jpa.hibernate.ddl-auto: "create-drop"